config/routes.rb
NeonlineMeetup02::Application.routes.draw do
  resources :stores

  resources :products

  get "home/index"

  devise_for :users
  root :to => 'home#index'

end

app/models/product.rb
# encoding: utf-8
require "#{Rails.root}/lib/extentions/active_record_extentions.rb"
class Product < ActiveRecord::Base
  include Publishable
  
  belongs_to :store
  
  # validar los estados
  ALLOWED_STATES = %w(active inactive_by_stock inactive_by_price inactive)
  has_statuses ALLOWED_STATES
  
  #precio minimo
  MINIMUM_PRICE = 1000
  MINIMUM_STOCK = 5
  
  validates :store_id,    :presence => true
  validates :cost,        :presence => true
  validates :price,       :presence => true
  
  
  delegate :name,
           :to          => :store,
           :prefix      => true,
           :allow_nill  => true
           

  def promo_message
   "- Las mejores ofertas en Farox.com!"
  end         

  
end

app/models/store.rb
class Store < ActiveRecord::Base
  
  has_many :products

  validates :name, :presence => true
  validates :legal_name, :presence => true
  validates :rut, :is_rut => true
  
  
  composed_of :rut, 
              :class_name => "RUT",
              :mapping => %w(rut full_rut),
              :converter => Proc.new { |full_rut| RUT.new(full_rut) }
  
              
  def by_rut(full_rut_as_string)
    where(:rut => RUT.new(full_rut_as_string))
  end
  
  

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(params[:store])

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!! 5
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : "NeonlineMeetup02"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    / Le styles
    :css
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    = stylesheet_link_tag "application", :media => "all"
    / Le fav and touch icons
    %link{:href => "images/favicon.ico", :rel => "shortcut icon"}/
    %link{:href => "images/apple-touch-icon.png", :rel => "apple-touch-icon"}/
    %link{:href => "images/apple-touch-icon-72x72.png", :rel => "apple-touch-icon", :sizes => "72x72"}/
    %link{:href => "images/apple-touch-icon-114x114.png", :rel => "apple-touch-icon", :sizes => "114x114"}/


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"}NeonlineMeetup02
          .container.nav-collapse
            %ul.nav
              %li{:class=>("active" if controller_name == "products")}= link_to "Products", products_path
              %li{:class=>("active" if controller_name == "stores")}= link_to "Stores", stores_path
              %li= link_to "Users", "/path3"

    .container

      .content
        .row
          .span9
            = yield

    
      %footer
        %hr
        %p Neonline 2012
    /
      Le javascript
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/products/_form.html.haml
= render :partial => "shared/flash_alerts"

%fieldset

  = f.input :title, :input_html=>{:class => 'text_field span5'}, :hint => 'Mínimum 6 characters'

  = f.input :description, :input_html=>{:class => 'text_area span5'}


  = f.input :cost, :class => 'number_field'

  = f.input :price, :class => 'number_field'

  = f.association :store, :prompt=> "Select the store..."
  
  = f.input :status, :collection => Product::ALLOWED_STATES, :prompt=> "Select the status..."

  .form-actions
    %button{:class => "btn btn-primary", :type => "submit"} Save product
    or
    = link_to "Cancel", products_path

app/views/products/edit.html.haml
.page-header
  %h2
    Edit Product

= simple_form_for @product, :url => product_path(@product), :html => { :class => "edit_product form-horizontal", :id => "edit_product" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/products/index.html.haml
.page-header
  %h2 
    Products
    .pull-right
      = link_to new_product_path, :class => 'btn' do
        %i.icon-plus
        New product
    .clear

.subnav
  .pull-right
    %form.form-inline.form-search
      %input.search-query.span2{:type=>"text", :placeholder=>"Search..."}
      %button.btn
        %i.icon-search
  %ul.nav.nav-pills
    %li 
      =link_to "Filter 1", ""
    %li
      =link_to "Filter 2", ""
    %li
      =link_to "Filter 3", ""

= render :partial => "shared/flash_alerts"
  
%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.product.title", :default => t("activerecord.labels.title", :default => "Title"))
      
      %th
        = t("activerecord.attributes.product.store_name", :default => t("activerecord.labels.store_name", :default => "Store"))
        
      %th
        = t("activerecord.attributes.product.status", :default => t("activerecord.labels.status", :default => "Status"))
      %th Created at
      %th Actions
  %tbody
    - @products.each do |product|
      %tr
        %td= product.id
        %td= link_to product.title, product_path(product)
        %td= product.store_name
        %td= product.status_name
        %td= product.created_at
        %td
          = link_to "Show", product_path(product)
          = link_to "Edit", edit_product_path(product)
          = link_to "Destroy", product_path(product), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"

app/views/products/new.html.haml
.page-header
  %h2
    New Product
    
= simple_form_for @product, :url => products_path, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/products/show.html.haml
.page-header
  %h2 
    = @product.title
    .pull-right
      = link_to edit_product_path(@product), :class => 'btn' do
        %i.icon-pencil
        Edit
    .clear

= render :partial => "shared/flash_alerts"

%label{:class => "label"}= t("activerecord.attributes.product.title", :default => t("activerecord.labels.title", :default => "Title")) + ":"
%p= @product.title
%label{:class => "label"}= t("activerecord.attributes.product.description", :default => t("activerecord.labels.description", :default => "Description")) + ":"
%p= @product.description
%label{:class => "label"}= t("activerecord.attributes.product.cost", :default => t("activerecord.labels.cost", :default => "Cost")) + ":"
%p= @product.cost
%label{:class => "label"}= t("activerecord.attributes.product.price", :default => t("activerecord.labels.price", :default => "Price")) + ":"
%p= @product.price
%label{:class => "label"}= t("activerecord.attributes.product.store_name", :default => t("activerecord.labels.store_name", :default => "Store")) + ":"
%p= @product.store_name
%label{:class => "label"}= t("activerecord.attributes.product.status", :default => t("activerecord.labels.status", :default => "Status")) + ":"
%p= @product.status_name
%label{:class => "label"}= t("activerecord.attributes.product.friendly_url", :default => t("activerecord.labels.friendly_url", :default => "Friendly URL")) + ":"
%p= @product.friendly_url

.form-actions

  .pull-right  
    = link_to edit_product_path(@product), :class => 'btn' do
      %i.icon-pencil
      Edit
    
    = link_to product_path(@product), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger' do
      %i.icon-trash.icon-white
      Delete
      
  .clear
    
= link_to products_path, :class => '' do
  « Volver
    

app/views/shared/_flash_alerts.html.haml
- unless flash[:notice].blank?
  .alert.alert-success
    %a.close{"data-dismiss" => "alert"} ×
    = flash[:notice]
    
- unless flash[:error].blank?
  .alert-message.error
    = content_tag :div, flash[:error]
- unless flash[:alert].blank?
  .alert-message.warning
    = content_tag :div, flash[:alert]

app/views/stores/_form.html.haml
= render :partial => "shared/flash_alerts"
%fieldset

  = f.input :name, :input_html=>{:class => 'text_field span5'}

  = f.input :legal_name, :input_html=>{:class => 'text_field span5'}

  = f.input :rut, :input_html=>{:class => 'text_field span5'}, :label => 'RUT', :hint => "Incluya el dígito verificador"

  = f.input :description, :input_html=>{:class => 'text_area span5'}

.form-actions
  = f.button :submit, :class => 'btn btn-primary'
  or
  = link_to "Cancel", stores_path

app/views/stores/edit.html.haml
.page-header
  %h2
    Edit Store

= simple_form_for @store, :url => store_path(@store), :html => { :class => "edit_store form-horizontal", :id => "edit_store" } do |f|
  %input{:name => "_method", :type => "hidden", :value =>"put"}
  = render :partial => "form", :locals => {:f => f}

app/views/stores/index.html.haml
.page-header
  %h2 
    Stores
    .pull-right
      = link_to new_store_path, :class => 'btn' do
        %i.icon-plus
        New Store
    .clear

.subnav
  .pull-right
    %form.form-inline.form-search
      %input.search-query.span2{:type=>"text", :placeholder=>"Search..."}
      %button.btn
        %i.icon-search
  %ul.nav.nav-pills
    %li 
      =link_to "Filter 1", ""
    %li
      =link_to "Filter 2", ""
    %li
      =link_to "Filter 3", ""

= render :partial => "shared/flash_alerts"

%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th ID
      %th
        = t("activerecord.attributes.store.name", :default => t("activerecord.labels.name", :default => "Name"))
      %th RUT
      %th Created at
      %th Actions
  %tbody
    - @stores.each do |store|
      %tr
        %td= store.id
        %td= link_to store.name, store_path(store)
        %td= store.rut.to_s
        %td= store.created_at
        %td
          = link_to "Show", store_path(store)
          = link_to "Edit", edit_store_path(store)
          = link_to "Destroy", store_path(store), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"

app/views/stores/new.html.haml
= form_for @store, :url => stores_path, :html => { :class => :form } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/stores/show.html.haml
.page-header
  %h2 
    = @store.name
    .pull-right
      = link_to edit_store_path(@store), :class => 'btn' do
        %i.icon-pencil
        Edit
    .clear

= render :partial => "shared/flash_alerts"

%label{:class => "label"}= t("activerecord.attributes.store.name", :default => t("activerecord.labels.name", :default => "Name")) + ":"
%p= @store.name
%label{:class => "label"}= t("activerecord.attributes.store.legal_name", :default => t("activerecord.labels.legal_name", :default => "Legal name")) + ":"
%p= @store.legal_name
%label{:class => "label"}= t("activerecord.attributes.store.rut", :default => t("activerecord.labels.rut", :default => "Rut")) + ":"
%p= @store.rut
%label{:class => "label"}= t("activerecord.attributes.store.description", :default => t("activerecord.labels.description", :default => "Description")) + ":"
%p= @store.description

.form-actions

  .pull-right  
    = link_to edit_store_path(@store), :class => 'btn' do
      %i.icon-pencil
      Edit
    
    = link_to store_path(@store), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}", :class => 'btn btn-danger' do
      %i.icon-trash.icon-white
      Delete
      
  .clear
    
= link_to stores_path, :class => '' do
  « Volver